# -*- coding: utf-8 -*-
"""fastext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOD9zTS_s_v8I3soepOfGndr7iHUwC9c
"""

import pandas as pd
from sklearn.model_selection import train_test_split

!wget https://github.com/facebookresearch/fastText/archive/v0.9.2.zip

!unzip v0.9.2.zip

y# !cd fastText-0.9.2

# for python bindings :
!pip install /content/fastText-0.9.2/

import fasttext

df = pd.read_csv("/content/drive/My Drive/Teksir Takım Çalışması/Datasets/ttc_3600.csv" ,sep=",")

df

import re
for i,row in df.iterrows():
  text = row["text"]
  text = re.sub(r"[^A-ZĞÜŞİÖÇa-zğüışöç0-9]", " ", text)
  df["text"][i]=text

for i,row in df.iterrows():
  label = row["label"]
  text = " "+row["text"] 
  df["text"][i]=text
  label="__label__"+row["label"]
  df["label"][i]=label

df

df = df.sample(frac=1, random_state=41).reset_index(drop=True)
df

##!cat "/content/ttc_3600.csv" | shuf > /deneme_shuf.csv



df.to_csv("/df_train.csv", sep=",", index=False)

!head -n 3200 "/df_train.csv" > cooking.train
!tail -n 400 "/df_train.csv" > cooking.valid

model = fasttext.train_supervised(input="cooking.train", lr=1.0, epoch=25, wordNgrams=2 )

model.labels

model.save_model("model_cooking.bin")

model.test("cooking.valid")

